//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGymDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exercise
    {
        public Exercise()
        {
            this.Training = new HashSet<Training>();
        }
    
        public int Id { get; set; }
        public System.DateTime Start { get; set; }
        public System.DateTime End { get; set; }
        public string Place { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Training> Training { get; set; }
    }
}
