//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGymDev
{
    using System;
    using System.Collections.Generic;
    
    public partial class Training
    {
        public int Id { get; set; }
    
        public virtual Exercise Exercise { get; set; }
    }
}
